class NotDoneError(Exception):
    pass


class InitError(Exception):
    pass
